### ISSUE TITLE
FlightA while placing blocks

### ISSUE THREAD

**Issue by CamiciaNera** [Tecnio/AntiHaxerman#26]
Description: FlightA false flag while placing blocks

1. Use any client (in the clip i used Badlion 1.8.9)
2. Place blocks under the player and jump
3. Repeat this and the false flag will show

Video: https://streamable.com/vd5pem

 - OS: Windows 11
 - Plugin Version: 4.0-RC-2
 - Server Version: Spigot 1.8.8
 - Client Version and Type: Badlion 1.8.9 (can be replicate with any client)

**Comment by Tecnio** [comment]
Patched on next RC
