### ISSUE TITLE
FlightA while jumping on a slime

### ISSUE THREAD

**Issue by CamiciaNera** [Tecnio/AntiHaxerman#27]
Description: FlightA false flag while jumping on a slime

1. Use any client (in the clip i used Badlion 1.8.9)
2. Jump on a piston with a slime block
3. Press the button and the player will jump
4. While jumping the false flags will show

Video: https://streamable.com/ao42k9

-  OS: Windows 11
-   Plugin Version: 4.0-RC-2
-   Server Version: Spigot 1.8.8
-   Client Version and Type: Badlion 1.8.9 (can be replicate with any client)

**Comment by Tecnio** [comment]
Fixed
