### ISSUE TITLE
FlightD while exiting from a cobweb

### ISSUE THREAD

**Issue by CamiciaNera** [Tecnio/AntiHaxerman#28]
Description: FlightD false flag on cobweb

1. Use any client (in the clip i used Badlion 1.8.9)
2. Go on a block near to a cobweb and jump
3. When you are near from exit you will flag 

Video: https://streamable.com/9ef931

 - OS:Windows 11
 - Plugin: Version: 4.0-RC-2
 - Server Version: Spigot 1.8.8
 - Client Version and Type: Badlion 1.8.9 (can be replicate with any client)

**Comment by Tecnio** [comment]
Pushed changes fixing the bug, should be available on RC-4.
