### ISSUE TITLE
FlightA while eating and jumping

### ISSUE THREAD

**Issue by CamiciaNera** [Tecnio/AntiHaxerman#29]
Description: FlightA false flag while eating and jumping

1. Use any client (in the clip i used Badlion 1.8.9)
2. Eat while jumping and try to go on a block
3. You will false flag

Video: https://streamable.com/7rwglt

 - OS: Windows 11
 -  Plugin Version: 4.0-RC-2
 -  Server Version: Spigot 1.8.8
 -  Client Version and Type: Badlion 1.8.9 (can be replicate with any client)

**Comment by Tecnio** [comment]
Flight A was fixed with RC-3
