### ISSUE TITLE
Convert back to PacketEvents

### ISSUE THREAD

**Issue by overkidding** [Tecnio/antihaxerman#31]
**Is your feature request related to a problem? Please describe.**
Artemis Packet API has issues with viaversion or newer versions, throws exceptions, etc

**Describe the solution you'd like**
Move back the anticheat to PacketEvents 2.0

**Describe alternatives you've considered**
No other alternatives, PacketEvents >>>>

**Comment by Tecnio** [comment]
If it gets a major release again, sure.
