### ISSUE TITLE
 Error occurred while enabling AntiHaxerman 

### ISSUE THREAD

**Issue by F3F5** [Tecnio/antihaxerman#35]
**To Reproduce**
1. Upload to plugins folder
2. Start the server
3. See error

**Expected behavior**
https://pastebin.com/diVYGENT

**Environement (please complete the following information):**
 - OS: Ubuntu
 - Plugin Version 4.0.2
 - Server Version PandaSpigot 1.8.8

**Comment by F3F5** [comment]
PandaSpigot is a Paper fork

**Comment by F3F5** [comment]
It's a full log, just start server and get error

**Comment by Tecnio** [comment]
Like I said please try vanilla paper and please send the full server logs.

**Comment by F3F5** [comment]
developer is strange
